version: '3.4'

services:
  lab-files:
    image: lab-files
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 3000
      - 9229:9229
    command: node --inspect=0.0.0.0:9229 ./start/www